### ISSUE TITLE
Description of output

### ISSUE THREAD

**Issue by MarkusRinschen** [jdrudolph/photon#1]
Hi jdrudolph,
great software, might be rather useful! I wondered if you have a description of your outputs. I downloaded the output and got a GO_scores, predictions,.... file. I am particular confused about the prediction file.  
Maybe I missed it, but do you have some sort of documentation for this?

Thanks a lot!
M

**Comment by jdrudolph** [comment]
Thanks for your question. Here a small overview over the intended purpose of each output file:

1. `subnet.csv`: edges of the reconstructed signaling network. This is a sub-network of the input network (which is located at `/db/anat/H_sapiens.net`). The `subnet.csv` file can be e.g. imported into Cytoscape for further analysis.
2. `scores.csv`: signaling functionality scores devised by PHOTON. The 'Significant' column allows for easy filtering of the table. The other columns provide more detail on each step of the algorithm, i.e. calculating an empirical score, obtaining p-values, and finally FDR-corrected q-values.
3. `go_scores.csv`: details all GO annotation enrichment results for the reconstructed network. Filtering for the 'rejected' column (=1) will yield all sign. enriched categories. The naming of the other columns follows the convention of the [statistical test](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.hypergeom.html) used.
4. `predictions.csv`: contains information regarding the functional phosphorylation site prediction. The 'proba' column is the prediction score for each site (larger = better). If the phosphorylation site was part of the training set the 'label' column will be 'TRUE'. One should take special care when the training set was small, i.e. few sites with 'label' set to TRUE are in the data set.

I'm still working on the documentation, which will hopefully improve over time. Any feedback or further questions are appreciated!
