### ISSUE TITLE
Error when running with custom data: 'DataFrame' object has no attribute 'to_frame'

### ISSUE THREAD

**Issue by ma-bio21** [jdrudolph/photon#11]
Hi,
My docker installation runs fine with your sample data, but I get the above error when I try to use my own data. My data looks like this:

GeneID,Amino.Acid,Position,avg,Symbol
76707,S,1088,-0.997531494626,CLASP1
228140,S,429,-0.439277481319,TNKS1BP1
66922,S,186,0.988197913396,RRAS2
80288,S,21,0.00681367879271,BCL9L
80288,S,25,-0.894961248199,BCL9L
329877,S,1096,0.495977183684,DENND4C
71766,S,576,0.101136369347,RAVER1
16881,T,77,-0.387457567317,LIG1
226982,S,137,0.684338899602,EIF5B
68938,S,279,0.297268078714,ASPSCR1
21453,S,593,-0.933370239347,TCOF1
13178,S,11,0.610665511668,DCK

which seems to me to be the same format as your sample data, but I may have misinterpreted. Do you know what i'm doing wrong? many thanks, Sean

**Comment by jdrudolph** [comment]
I was able to reproduce the error. None of the `GeneID`s could be matched to the PPI network. The ids you provide in your example map to mouse genes. The network, however, is defined only for human entrez geneids.
You could try and map your ids to human using e.g. homologue proteins. We did exactly this in the PHOTON paper for one of the datasets. We obtained the mapping from MGI http://www.informatics.jax.org/downloads/reports/index.html#homology

**Comment by ma-bio21** [comment]
Yes I see - that makes sense. I'll try the mapping. Thanks for the help,  appreciate you taking the time to provide guidance.
