### ISSUE TITLE
Error on using custom data:   Cannot have number of folds n_folds=10 greater than the number of samples: 3.

### ISSUE THREAD

**Issue by sean-ocall** [jdrudolph/photon#12]
I get the above error when using my own data which looks like this (full dataset is longer): 

GeneID | Amino.Acid | Position | avg | Symbol
-- | -- | -- | -- | --
1027 | S | 17 | -1.96578 | CDKN1B
1822 | S | 79 | 1.360083 | ATN1
2353 | S | 36 | 1.306262 | FOS
2353 | S | 364 | 1.306262 | FOS
2886 | S | 7 | 0.897628 | GRB7
2886 | S | 66 | 0.897628 | GRB7
3607 | S | 42 | -1.074 | FOXK2
3607 | S | 424 | -1.074 | FOXK2
4008 | S | 159 | 1.146003 | LMO7
4041 | S | 161 | -5.64386 | LRP5
4041 | S | 1609 | -5.64386 | LRP5
4082 | S | 17 | -1.02915 | MARCKS

Is there any documentation for Photon? I tried to figure out where this error could be coming from but I haven't been able to. The data is human. 

Sorry if this is written somewhere but I've been making assumptions about exactly what the required information in the input files is and I should check with you if these are correct. I've been assuming that the 'avg' column is a log2 fold change, is this correct? Also is 'Symbol' supposed to be GENENAME as reported from here: http://www.uniprot.org/uploadlists/

A second, related data set gives the following error: 

This solver needs samples of at least 2 classes in the data, but the data contains only one class: False

Any ideas?

**Comment by jdrudolph** [comment]
From the error message it seems like the error occurs during 'functional site prediction'. The logistic regression model in PHOTON uses n-fold cross-validation for model training. It could be that for your specific data set, not enough training data is available for 10-fold validation.

Could you send me your data, so I can investigate exactly whats going on? You can 'anonymize' your dataset by removing the 'avg' column before sending it to me. I should be able to find the issue regardless.

Which documentation are you missing? The PHOTON manuscripts explains the concepts, and the code is available here. In general PHOTON is oblivious to how you generated the values in the 'avg' column. Log2 fold-change is the preferred choice. The 'Symbol' column is merely used for displaying gene symbols in the visualization and could be from any source.

**Comment by sean-ocall** [comment]
Hi, Thanks for responding. I think you are correct about there not being enough data. My collaborator had filtered the data and we were left with ~250 phosphorylation sites, whereas your example data has over 4000. I have just obtained the full list from him and the full data set runs without issue on Photon. 

As for documentation, I guess apart from the information you just gave me I was also looking to better understand the parameters on the main photon page (Signalling source etc.)

Many thanks!
