### ISSUE TITLE
PHOTON Web server gives an ANAT error while ANAT Cytoscape plugin works OK

### ISSUE THREAD

**Issue by ozgunbabur** [jdrudolph/photon#16]
I installed PHOTON with Docker, opened http://localhost:5000/, Downloaded the sample data, selected the sample data, set anchor = 1950, and pressed submit.

The web server gives me the below error popup.

HTTPConnectionPool(host='anat.cs.tau.ac.il', port=80): Max retries exceeded with url: /AnatWeb/AnatServer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5737217470>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

To check if ANAT server is working, I downloaded Cytoscape, selected and installed ANAT app, and made some query with successful results.

**Comment by jdrudolph** [comment]
The same workflow works for me, but server issues can occur from time to time... could you try again? If the problem persists then we can investigate further. Thanks!

**Comment by ozgunbabur** [comment]
I just tried again. The application progress up to the below screen.


![image](https://user-images.githubusercontent.com/1376779/36214827-454f0a52-115f-11e8-9d81-14529f506553.png)


Then I get the popup.


![image](https://user-images.githubusercontent.com/1376779/36215025-c4823eb6-115f-11e8-9dac-8cf358042013.png)

**Comment by jdrudolph** [comment]
thanks for the report. I'll see what I can do for you

**Comment by jdrudolph** [comment]
I just ran the latest image of PHOTON on my computer and everything worked fine

    docker pull jdrudolph/photon
    docker run -d -p 5000:5000 jdrudolph/photon

Maybe there is some issue with the internet connection of the docker container. This could also explain why there was no error with the cytoscape plugin.

To check internet connectivity from within the container run

    docker run -i -t --entrypoint /bin/bash jdrudolph/photon
    ping www.google.com

you should see lines like this (CTRL+C to exit)

    64 bytes from 216.58.207.132: icmp_seq=0 ttl=55 time=39.382 ms

**Comment by ozgunbabur** [comment]
You are right, my docker cannot connect to the internet.
I tried [this](https://odino.org/cannot-connect-to-the-internet-from-your-docker-containers/) and [this](https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet) but could not solve it.

**Comment by jdrudolph** [comment]
I wouldn't know what to do, other than googleing the error message and trying out the suggestions...
If you are using a linux machine, or have access to a virtual machine with linux, you could try running PHOTON directly. I will close this issue for now since it is not directly related to the PHOTON code.
