### ISSUE TITLE
Link to tutorial data appears broken

### ISSUE THREAD

**Issue by 4000qtrap** [jdrudolph/photon#17]
Hi-

I'm new to Perseus and Photon but trying to learn via your tutorial. However, the link to the example data on the tutorial page (https://github.com/jdrudolph/photon/blob/master/docs/Perseus/tutorial.md) appears broken.

-Cheers,
Jason

**Comment by jdrudolph** [comment]
Thank you for reporting this issue! Please do open another issue if you find any other problems with the tutorial.

Best,
Jan
