### ISSUE TITLE
Find annotation file from UniProt to ENSP

### ISSUE THREAD

**Issue by LuisFranciscoHS** [jdrudolph/photon#20]
Hello Jan!

I am following the turorial at https://github.com/jdrudolph/photon/blob/master/docs/Perseus/tutorial.md#phosphorylation-data and in step 3. I can't find the file `mainAnnot.homo_sapiens.txt.gz`. Where can I get it?

![image](https://user-images.githubusercontent.com/23653149/53912052-5c383d00-4058-11e9-87d4-b2e28516f460.png)

And also, I see in the paper that the application can run in a web browser interface independently of Perseus. How do you run it?

Best regards,
Francisco.

**Comment by jdrudolph** [comment]
Hi Francisco,

you can download annotations for Perseus at http://annotations.perseus-framework.org.
The old way of running PHOTON stand-alone in the browser was discontinued in favor of running it through Perseus. You can check out https://www.biorxiv.org/content/10.1101/447268v2 for a description of Perseus' latest network analysis capabilities.
If you have experience with Docker you might be able to get PHOTON to run, but I cannot provide support for this approach anymore. Alternatively, if you know some Python, you can run PHOTON directly in Python.

I hope this helps. Let me know if you get stuck somewhere in the tutorial.
