### ISSUE TITLE
Can't change column type

### ISSUE THREAD

**Issue by cheininger** [jdrudolph/photon#23]
Good day

I am fairly new to phosphoproteomics and started using PHOTON on my university's PC recently. I am now trying to get Perseus and PHOTON to run on my personal PC as well, first trying the PHOTON tutorial data, however today I encountered an interesting error.
The error occurs right at the start when I try to change the column type of the combined_score column to Numerical. And most frustatingly, the error appears on both my home PC and my PC at the university, where I tried to check wether it was specific to one PC, but it was not. 
![perseus_err_change_column_type](https://user-images.githubusercontent.com/52415030/60441642-b8325d00-9c17-11e9-8e34-85963f8672f9.PNG)
(For non-German-speakers, the error reads "Index was outside the bounds of the array. It cannnot be negative of smaller than the collection", roughly translated)
This does not look like a Perseus-specific error to me, however I figured someone might have run into this problem before and knows a solution.
I am most grateful for any help

-C

**Comment by jdrudolph** [comment]
Please make sure that you are using english language settings on your computer. Differences in the number format e.g. 0,1 instead of 0.1 might cause this error.
