### ISSUE TITLE
excutor

### ISSUE THREAD

**Issue by Sarkawt-Hamad** [jdrudolph/photon#24]
Dear Rudolph,

I am new in the phosphoproteomics data analysis and I want to use PHOTON for one of my experiment. I follow all steps as you have explained in tutorial videos, and everything went fine, except at the end step when I run PHOTON this error always come out (joblib.external.loky.process_excutor.RemoteTraceback). I have no idea why this is always coming out when I have up to date everything.

Please, do you have any suggestion how to overcome this error?

Best regards,

Sarkawt

**Comment by jdrudolph** [comment]
Hi Sarkawt,
this might be a duplicate of #22.
I cannot reproduce this error on my side. Please feel free to reopen if neccessary.
Best, Jan
