### ISSUE TITLE
I always got error message while processing Photon.

### ISSUE THREAD

**Issue by PsuperGirl** [jdrudolph/photon#29]
![WeChat Image_20200312181352](https://user-images.githubusercontent.com/62112845/79590404-46100380-80d7-11ea-8639-8ed6cf334f29.png)
Hi Jan,

Currently, I am trying to apply Photon to analyze some phosphoproteome data. But I always got this error message. Do you have any suggestions to solve this problem?

Thank you very much first
Best,
Juan

**Comment by jdrudolph** [comment]
Could you please describe how I can reproduce this error on my computer? Thank you!
