### ISSUE TITLE
Could not load type 'PerseusApi.Utils.PerseusFactory

### ISSUE THREAD

**Issue by DoubleHelixAlchemist** [jdrudolph/photon#31]
Hello Jan,

 I am trying to generate the network collection, following your tutorial. I have done all the processing on the matrices and everything looks fine, however, when I click "ok" after "basic"-> "from matrix" -> check "Network is directed", I get an error message saying "Could not load type 'PerseusApi.Utils.PerseusFactory'"! Am I missing some plug-in? 

Thank you very much for your time!

**Comment by jdrudolph** [comment]
this is a bug in Perseus. hopefully this will be fixed in the next version. https://groups.google.com/g/perseus-list/c/R-ugG7IfiX8

**Comment by DoubleHelixAlchemist** [comment]
Thank you for the explanation! I hope you have a nice weekend!
