### ISSUE TITLE
Photon analysis

### ISSUE THREAD

**Issue by IsalineMs** [jdrudolph/photon#34]
Hi,

I have a few questions concerning the analysis.

1)What is the format of the data input? I have label free phosphoproteomics from 2 groups : WT vs disease. Do I just use the log2FC column after doing a t-test between the groups and connect that to the network?
2)Once I have the network collection and matrix from Photon analysis, how do I know which proteins are affecting the phosphorylation the most? Do you just filter the Nodes with the signaling score? If I only want to see the kinases, is it right to add the Keywords annotations and filter these with kinases? What about the ones not detected in my dataset? 
3)Is it possible to get a legend when visualising? I suppose the darker the node the more phosphorylated it is. 
4)l haven't been able to find a tutorial for the KSEA analysis within Perseus. Is there any? if not would you have any tips (as I assume it is very similar to Photon, just need to create a different network). 

Thanks heaps

Cheers,

Isaline

**Comment by jdrudolph** [comment]
Thanks for your interest, however this isse tracker is exclusively for issues regarding the code of PHOTON. Instead, please refer to the MaxQuant or Perseus google groups for help from the community and the Perseus team.
