### ISSUE TITLE
Data Input

### ISSUE THREAD

**Issue by IsalineMs** [jdrudolph/photon#36]
Hi, 

I am working with label free phosphoproteomics data, 2 genotypes (Disease-WT), 4 biological replicates per genotype.
Is it correct to use the log FC Disease/WT (one column) as the input data for Photon? 
Thanks

Isaline

**Comment by jdrudolph** [comment]
Hi,

this bug tracker is not intended for general user questions. Maybe the Perseus or MaxQuant google groups would be a better place to ask. With that out of the way you can certainly apply PHOTON to log FC data. At it's core PHOTON is completely oblivious as to what kind of data you feed it. You just have to interpret the data in the chosen context.
Check out https://science.sciencemag.org/content/366/6462/eaav3617.abstract and https://www.sciencedirect.com/science/article/pii/S2405471216303696 for examples.

Best, Jan
