### ISSUE TITLE
Can not open the STRING Network for phosphoproteomic analysis

### ISSUE THREAD

**Issue by shayankhozooei** [jdrudolph/photon#38]
Dear Jan,

I am trying to do network analysis for phosphoproteomics accroding to the Youtube video of Perseus https://www.youtube.com/watch?v=svHRuH148QY&t=1560s
I used the newest version of Perseus, however, In was not able to connect to the PHOTON. After searching I realized that I need to use the older version of Perseus (1.6.14.0) to be able to connect to the PHOTON. Now there is another problem. In this vesrion (1.6.14.0) I am not able to get the STRING network from matrix and I get an error for that. Do you have any solution for that? I attached the error photo.
![Screenshot (2)](https://user-images.githubusercontent.com/86058913/122405149-17621700-cf80-11eb-8caa-6d183e4a35c7.png)
![Screenshot (3)](https://user-images.githubusercontent.com/86058913/122405174-1f21bb80-cf80-11eb-814d-8f340ff39758.png)

Thank you in advance,

Best regards,
Shayan Khozooei

**Comment by jdrudolph** [comment]
Hi!
This issue appears to be Perseus related and not caused by PHOTON. https://groups.google.com/g/perseus-list/c/R-ugG7IfiX8. You can get in contact with the Perseus team via the google group. Hopefully they'll be able to resolve the error. Unfortunately I can't help here.

Best Jan
