### ISSUE TITLE
any progress indicator available?

### ISSUE THREAD

**Issue by krzysztofpawlowskiWULS** [jdrudolph/photon#6]
Hi,

I started Photon with a small dataset (128 phosphosites in some 80 proteins).
The job has been running for 20 hours (or so I see when using "docker ps" command)
Yet, in the browser I still see the message "working on job with id:....".

Could my job be hanging? How do I check the progress of my job?

Any suggestions will be appreciated,
Krzysztof

**Comment by jdrudolph** [comment]
Dear Krzysztof,

currently there is no progress indicator, but jobs should not be running longer than a few hours, especially for small data sets. Is your computer still 'busy' and using the CPU? Please update the image using `docker pull jdrudolph/photon` and try again after restarting the container.

Best, Jan

**Comment by jdrudolph** [comment]
I added progress logging to the development version of PHOTON. You can try it by running

    docker pull jdrudolph/photon:dev
    docker run -d -p 5000:5000 jdrudolph/photon:dev

Please tell me at what stage PHOTON is stuck.

**Comment by krzysztofpawlowskiWULS** [comment]
Dear Jan,
Thanks for adding the progress indicator!

When I'm using the dev version, my PHOTON job gets stuck at stage 3:
"Progress message: 3/5 calculated scores, infering subnetwork using ANAT..."

It happens only when I submit my own dataset. I suspect that there may be too few known interactions between proteins from my dataset for ANAT to perform well.

When I submit your sample dataset, I get full results rather quickly.

For my "stuck" job, is there a way to get the intermediate data, 
e.g. signaling functionality scores?

Best,
Krzysztof

**Comment by jdrudolph** [comment]
Using the browser interface there is no way to obtain intermediate results. You could consider using PHOTON from a linux machine (command line), where each step of the analysis could be run independently.
