### ISSUE TITLE
PPI input data

### ISSUE THREAD

**Issue by JessQuevza** [jdrudolph/photon#9]
Hi Jan!

I downloaded the data from http://cs.tau.ac.il/~jandanielr/db.tar.gz (see [Dockerfile](https://github.com/jdrudolph/photon/blob/master/Dockerfile)).
So my question is, what does each column in the ANAT file (`H_sapiens.net`) represent?

I would like to upload my own PPI network and I read this is possible (see [issue #8](https://github.com/jdrudolph/photon/issues/8)) but first I am interested in gaining more experience with your own network.

Many thanks!
Best,
Jessica

**Comment by jdrudolph** [comment]
You can see all code related to loading the network in [phos/data/network.py](https://github.com/jdrudolph/photon/blob/master/phos/data/network.py). The columns correspond to 'source', 'target', 'confidence', 'directed'. For more explanation on the edge confidence measure, see the 'Notes and Remarks' section in the [ANAT paper](http://stke.sciencemag.org/content/4/196/pl1.full). In PHOTON all edges are assumed to be undirected.
